"""empty message

Revision ID: 691dd39b018e
Revises: 3824f9fc6666
Create Date: 2020-04-28 04:17:41.546223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691dd39b018e'
down_revision = '3824f9fc6666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_confirmation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_confirmation')
    # ### end Alembic commands ###
